#!/bin/sh

exec docker run \
    --rm \
    --tty \
    --detach \
    --device=/dev/net/tun \
    --name=openvpn-client \
    --cap-add=NET_ADMIN \
    --publish 127.0.0.1:1083:1083 \
    --add-host git.sdb247.com:172.16.1.113 \
    --volume "$(realpath "$1"):/etc/openvpn/:ro" \
    --sysctl net.ipv6.conf.all.disable_ipv6=0 \
    docker-openvpn-socks
